export * from './Dev';
export { default as Splash } from './Splash';
export { default as Onboarding } from './Onboarding';
export { default as Signup } from './Signup';
export { default as Login } from './Login';
export { default as Home } from './Home';
export { default as MenuList } from './MenuList';
export { default as MenuItem } from './MenuItem';
export { default as MyCart } from './MyCart';
export { default as OrderList } from './OrderList';
export { default as Location } from './Location';
export { default as PaymentMethod } from './PaymentMethod';
export { default as ConfirmOrder } from './ConfirmOrder';
export { default as OrderSuccess } from './OrderSuccess';
export { default as OrderFailed } from './OrderFailed';
export { default as OrderStatus } from './OrderStatus';
export { default as Feedback } from './Feedback';
export { default as ReservationList } from './ReservationList';
export { default as CreateReservation } from './CreateReservation';
export { default as ReservationSuccess } from './ReservationSuccess'
export { default as Profile } from './Profile'
export { default as EditProfile } from './EditProfile'
export { default as ChangePassword } from './ChangePassword'
export { default as Language } from './Language'
export { default as AboutUs } from './AboutUs'