export * from './Dev';
export { default as Splash } from './Splash';
export { default as Onboarding } from './Onboarding';
export { default as Signup } from './Signup';
export { default as Login } from './Login';
export { default as Home } from './Home';
export { default as MenuList } from './MenuList';
export { default as MenuItem } from './MenuItem';
export { default as MyCart } from './MyCart';
export { default as OrderList } from './OrderList';
export { default as Location } from './Location';
export { default as PaymentMethod } from './PaymentMethod';
export { default as ConfirmOrder } from './ConfirmOrder';
