export const NAVIGATORS = {
  DEV: 'DevNavigatior',
  PUBLIC: 'PublicNavigatior',
  CORE: 'CoreNavigatior',
  MENU: 'MenuNavigatior',
  ORDER: 'OrderNavigatior',
  RESERVATION: 'ReservationNavigatior',
  CART: 'CartNavigatior',
  PROFILE: 'ProfileNavigatior',
} as const;

export const SCREENS = {
  DEV_MENU: 'DevMenu',
  DEV_STORY_BOOK: 'DevStoryBook',
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  SIGNUP: 'Signup',
  LOGIN: 'Login',
  HOME: 'Home',
  MENU_LIST: 'MenuList',
  MENU_ITEM: 'MenuItem',
  MY_CART: 'MyCart',
  LOCATION: 'Location',
  PAYMENT_METHOD: 'PaymentMethod',
  CONFIRM_ORDER: 'ConfirmOrder',
  ORDER_SUCCESS: 'OrderSuccess',
  ORDER_FAILED: 'OrderFailed',
  ORDER_STATUS: 'OrderStatus',
  FEEDBACK: 'Feedback',
  ORDER_LIST: 'OrderList',
  RESERVATION_LIST: 'ReservationList',
  CREATE_RESERVATION: 'CreateReservation',
  RESERVATION_SUCCESS: 'ReservationSuccess',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  CHANGE_PASSWORD: 'ChangePassword',
  LANGUAGE: 'Language',
  FAQS: 'Faqs',
  ABOUT_US: 'AboutUs',
} as const;
